# Generated by Django 5.2.16 on 2026-08-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
