# Generated by Django 5.2.16 on 2026-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Business', max_length=180)),
                ('logo', models.ImageField(blank=True, upload_to='company/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('invoice_prefix', models.CharField(default='INV', max_length=12)),
                ('invoice_footer', models.TextField(default='Thank you for your business.')),
                ('bank_details', models.TextField(blank=True)),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('upi_qr_code', models.ImageField(blank=True, upload_to='company/')),
                ('digital_signature', models.ImageField(blank=True, upload_to='company/')),
                ('terms_and_conditions', models.TextField(default='Goods once sold will not be taken back. Payment is due as per invoice terms.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
