# Generated by Django 5.2.16 on 2026-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'processing'), ('completed', 'completed'), ('cancelled', 'cancel')], default='draft', max_length=20),
        ),
    ]
